apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  type: LoadBalancer
  ports:
    - name: api-service-port
      port: 8000
      targetPort: "api-proxy-port"
      protocol: TCP
  selector:
    app: api-proxy
