apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: web-proxy
    spec:
      containers:
        - name: web-proxy
          image: microhq/micro:kubernetes
          args:
            - "api"
            - "--handler=web"
          env:
            - name: MICRO_API_ADDRESS
              value: ":8080"
          ports:
            - containerPort: 8080
              name: web-proxy-port
