apiVersion: v1
kind: Service
metadata:
  name: web-proxy
  labels:
    app: web-proxy
spec:
  type: LoadBalancer
  ports:
    - name: web-proxy-port
      port: 8080
      targetPort: "web-proxy-port"
      protocol: TCP
  selector:
    app: web-proxy
